#!/usr/bin/env php
<?php

require_once(dirname(__FILE__) . '/../vendor/autoload.php');

$dotenv = Dotenv\Dotenv::createImmutable(dirname(__FILE__) . '/..');
$dotenv->load();

require_once(dirname(__FILE__).'/yiic.php');
